#!/bin/sh

pack() {
	FILES=$(find . -name '*.blob')

	for file in $FILES; do
		rm $(echo $file | sed 's|\.blob$||g')
	done
}

unpack() {
	if [ "$1" = "" ]; then
		FILES=$(find . -name '*.blob')
	else
		FILES=$1
	fi

	for file in $FILES; do
		blob=$(echo $file | sed 's|\.blob$||g')

		[ ! -f "$blob" ] && wget -O $blob $(cat $file)
	done
}

add() {
	ADDR=$1
	NAME=$(basename $ADDR)

	echo "$ADDR" > $NAME.blob
	unpack $NAME.blob
}

remove() {
	FILE=$1

	rm $FILE
	rm $FILE.blob
}

usage() {
	echo "Usage: $0 [OPTION] ..."
	echo "Links binary blobs from URLs into git repositories."
	echo
	echo "Options:"
	echo "    -h    This help message"
	echo "    -p    Pack the repository, removes blobs"
	echo "    -u    Unpack the repository, downloads blobs"
	echo "    -a    Adds the blob at the specified URL to the repo"
	echo "    -r    Removes the specified blob from the repo"
	exit
}

while getopts ":hpua:r:" args; do
	case "$args" in
	p)
		pack
		;;
	u)
		unpack
		;;
	a)
		add $OPTARG
		;;
	r)
		remove $OPTARG
		;;
	h|*)
		usage
		;;
	esac
done
shift $((OPTIND-1))
